findredundantdeps.in: cosmetic changes

diff --git a/findredundantdeps.in b/findredundantdeps.in
--- a/findredundantdeps.in
+++ b/findredundantdeps.in
@@ -7,8 +7,8 @@
 ######################################################################
 
 fatal() {
-  echo >&2 "@ARGV0@: $1"
-  exit 1
+	echo >&2 "@ARGV0@: $1"
+	exit 1
 }
 
 ######################################################################
@@ -16,16 +16,16 @@ fatal() {
 ######################################################################
 
 findredundantdeps() {
-  _DEPS=$(pkgman dep --all "$1") || exit 3
+	_DEPS=$(pkgman dep --all "$1") || exit 3
 
-  # Intentional.
-  # shellcheck disable=2086
-  pkgman dep --all --recursive --full "$1" |
-    grep -E "($(echo $_DEPS | tr ' ' '|'))$"
+	# Intentional.
+	# shellcheck disable=2086
+	pkgman dep --all --recursive --full "$1" |
+		grep -E "($(echo $_DEPS | tr ' ' '|'))$"
 }
 
 show_uniq() {
-  tr ' ' '\n' | sort | uniq -u
+	tr ' ' '\n' | sort | uniq -u
 }
 
 ######################################################################
@@ -33,7 +33,7 @@ show_uniq() {
 ######################################################################
 
 print_help() {
-  cat <<EOF
+	cat <<EOF
 Usage: @ARGV0@ [OPTION] PKGNAME
 Find (un)necessary dependencies of the package.
 
@@ -44,44 +44,54 @@ EOF
 }
 
 print_version() {
-  echo "@ARGV0@ (pkgmaint) @VERSION@"
+	echo "@ARGV0@ (pkgmaint) @VERSION@"
 }
 
 parse_options() {
-  eval set -- "$(
-    getopt -n "@ARGV0@" -a -l "unique,version,help" -o ":uvh" -- "$@"
-  )"
-  while true; do
-    case $1 in
-    -u| --unique) SHOW_UNIQ_CMD=show_uniq     ;;
-    -v|--version) print_version      ; exit 0 ;;
-    -h|   --help) print_help         ; exit 0 ;;
-              --) shift              ; break  ;;
-               *) fatal "unknown option: $1"  ;;
-    esac
-    shift
-  done
+	eval set -- "$(
+		getopt  -n "@ARGV0@" -a           \
+			-l "unique,version,help"  \
+			-o ":uvh" -- "$@"
+	)"
+	while true; do
+		case $1 in
+		-u| --unique) SHOW_UNIQ_CMD=show_uniq     ;;
+		-v|--version) print_version      ; exit 0 ;;
+		-h|   --help) print_help         ; exit 0 ;;
+		          --) shift              ; break  ;;
+		           *) fatal "unknown option: $1"  ;;
+		esac
+		shift
+	done
 
-  SHOW_UNIQ_CMD=${SHOW_UNIQ_CMD:-cat}
-  PKGNAME=$*
+	SHOW_UNIQ_CMD=${SHOW_UNIQ_CMD:-cat}
+	PKGNAME=$*
 
-  set -- $PKGNAME
-  case $# in
-  0) fatal "missing argument"   ;;
-  1)                            ;;
-  *) fatal "too many arguments" ;;
-  esac
+	set -- $PKGNAME
+	case $# in
+	0) fatal "missing argument"   ;;
+	1)                            ;;
+	*) fatal "too many arguments" ;;
+	esac
 }
 
 main() {
-  parse_options "$@"
-  findredundantdeps "$PKGNAME" | $SHOW_UNIQ_CMD
+	parse_options "$@"
+	findredundantdeps "$PKGNAME" | $SHOW_UNIQ_CMD
 }
 
 ######################################################################
 
+# -e: Exit if command return status greater than 0
+# -f: Disable globbing *?[]
+set -ef
+
+# Globals.
 export LC_ALL=POSIX
+
+######################################################################
+
 main "$@"
 
-# vim:sw=2:ts=2:sts=2:et:cc=72:tw=70
+# vim: cc=72:tw=70
 # End of file.
