finddisowned.in: print to stderr abort message

diff --git a/finddisowned.in b/finddisowned.in
--- a/finddisowned.in
+++ b/finddisowned.in
@@ -105,7 +105,8 @@ main() {
 }
 
 interrupted() {
-	echo "=======> Aborted."
+	echo >&2 ""
+	echo >&2 "=======> Aborted."
 	exit 1
 }
 
