finddisowned.in: restyle, use GNU getopt(1)

diff --git a/finddisowned.in b/finddisowned.in
--- a/finddisowned.in
+++ b/finddisowned.in
@@ -3,40 +3,40 @@
 # See COPYING and COPYRIGHT files for corresponding information.
 
 finddisowned() {
-	# https://tldp.org/LDP/abs/html/exitcodes.html
-	# 126 - Command invoked cannot execute.
-	TMPFILE1=$(mktemp) || exit 126
-	TMPFILE2=$(mktemp) || exit 126
+  # https://tldp.org/LDP/abs/html/exitcodes.html
+  # 126 - Command invoked cannot execute.
+  TMPFILE1=$(mktemp) || exit 126
+  TMPFILE2=$(mktemp) || exit 126
 
-	echo "Get all known files..." 1>&2
+  echo "Get all known files..." 1>&2
 
-	sort -u "$ROOT/var/lib/pkg/db" > "$TMPFILE1"
+  sort -u "$ROOT/var/lib/pkg/db" > "$TMPFILE1"
 
-	echo "Get paths from config..." 1>&2
+  echo "Get paths from config..." 1>&2
 
-	#PATHS=$(xargs < "$(readlink -f "$CONF")")
-	while read -r _path; do
-		# skip comments and empty lines
-		case $_path in \#* | "" ) continue ;; esac
+  #PATHS=$(xargs < "$(readlink -f "$CONF")")
+  while read -r _path; do
+    # skip comments and empty lines
+    case $_path in \#* | "" ) continue ;; esac
 
-		PATHS="$PATHS $_path"
-	done < "$(readlink -f "$CONF")"
+    PATHS="$PATHS $_path"
+  done < "$(readlink -f "$CONF")"
 
-	(
-	cd "${ROOT:-/}" || exit 1
+  (
+  cd "${ROOT:-/}" || exit 1
 
-	# Intentional word splitting for PATHS.
-	# shellcheck disable=2086
-	find $PATHS \( -type d -printf '%p/\n' -o -print \) |
-		sort > "$TMPFILE2"
-	)
+  # Intentional word splitting for PATHS.
+  # shellcheck disable=2086
+  find $PATHS \( -type d -printf '%p/\n' -o -print \) |
+    sort > "$TMPFILE2"
+  )
 
-	comm -23 "$TMPFILE2" "$TMPFILE1"
+  comm -23 "$TMPFILE2" "$TMPFILE1"
 }
 
 print_help() {
-	cat <<EOF
-Usage: finddisowned [OPTION]...
+  cat <<EOF
+Usage: @ARGV0@ [OPTION]...
 Find files that are disowned by package manager.
 
   -r, --root=PATH     specify an alternative root directory
@@ -46,73 +46,49 @@ Find files that are disowned by package manager.
 EOF
 }
 
-assert_option_has_arg() {
-	if [ ! "$1" ]; then
-		echo >&2 "$PROGRAM: option $2 requires an argument"
-		exit 1
-	fi
+print_version() {
+  echo "@ARGV0@ (pkgmaint) @VERSION@"
+}
+
+parse_options() {
+  eval set -- "$(
+    getopt -n "@ARGV0@" -a -l "root:,config:,version,help" \
+      -o "r:c:vh" -- "$@"
+  )"
+  while true; do
+    case $1 in
+    -r|   --root) ROOT=$2                   ; shift  ;;
+    -c| --config) CONF=$2                   ; shift  ;;
+    -v|--version) print_version             ; exit 0 ;;
+    -h|   --help) print_help                ; exit 0 ;;
+              --) shift                     ; break  ;;
+               *) echo >&2 "internal error" ; exit 1 ;;
+    esac
+    shift
+  done
 }
 
 main() {
-	while [ "$1" ]; do
-		case $1 in
+  parse_options "$@"
 
-		-r|--root)
-			ROOT=$2
-			assert_option_has_arg "$ROOT" "-r/--root"
-			shift
-			;;
-		-r*|--root=*)
-			ROOT="$(echo "$1" | sed 's/^-\(-root\|r\)//')"
-			assert_option_has_arg "$ROOT" "-r/--root"
-			;;
+  CONF=${CONF:-"$ROOT/etc/finddisowned.conf"}
+  if [ ! -e "$CONF" ]; then
+    echo >&2 "@ARGV0@: configuration file not found: $CONF"
+    exit 2
+  fi
 
-		-c|--config)
-			CONF=$2
-			assert_option_has_arg "$CONF" "-c/--config"
-			shift
-			;;
-		-c*|--config=*)
-			CONF="$(echo "$1" | sed 's/^-\(-config\|c\)//')"
-			assert_option_has_arg "$CONF" "-c/--config"
-			;;
-
-		-v|--version)
-			echo "$PROGRAM (pkgmaint) @VERSION@"
-			exit 0
-			;;
-		-h|--help)
-			print_help
-			exit 0
-			;;
-
-		*)
-			echo >&2 "$PROGRAM: invalid option $1"
-			exit 1
-			;;
-
-		esac
-		shift
-	done
-
-	CONF=${CONF:-"$ROOT/etc/finddisowned.conf"}
-	if [ ! -e "$CONF" ]; then
-		echo >&2 "$PROGRAM: can't find $CONF file"
-		exit 2
-	fi
-
-	finddisowned
+  finddisowned
 }
 
 interrupted() {
-	echo >&2 ""
-	echo >&2 "=======> Aborted."
-	exit 1
+  echo >&2 ""
+  echo >&2 "=======> Aborted."
+  exit 1
 }
 
 atexit() {
-	[ -f "$TMPFILE1" ] && rm "$TMPFILE1"
-	[ -f "$TMPFILE2" ] && rm "$TMPFILE2"
+  [ -f "$TMPFILE1" ] && rm "$TMPFILE1"
+  [ -f "$TMPFILE2" ] && rm "$TMPFILE2"
 }
 
 trap "interrupted" HUP  INT  QUIT  TERM
@@ -121,11 +97,10 @@ trap "atexit"      EXIT
 export LC_ALL=POSIX
 
 # Globals.
-readonly PROGRAM="${0##*/}"
 TMPFILE1=
 TMPFILE2=
 
 main "$@"
 
-# vim:cc=72:tw=70
+# vim:sw=2:ts=2:sts=2:et:cc=72:tw=70
 # End of file.
