big cleanup

diff --git a/finddisowned.in b/finddisowned.in
--- a/finddisowned.in
+++ b/finddisowned.in
@@ -10,9 +10,8 @@ info() {
 	echo "=======> $1"
 }
 
-fatal() {
-	echo "@ARGV0@: $1" 1>&2
-	exit 1
+error() {
+	info "ERROR: $1"
 }
 
 ######################################################################
@@ -31,8 +30,8 @@ interrupted() {
 
 # shellcheck disable=2317
 atexit() {
-	[ -f "$TMPFILE1" ] && rm -f "$TMPFILE1"
-	[ -f "$TMPFILE2" ] && rm -f "$TMPFILE2"
+	if [ -f "$TMPFILE1" ]; then  rm -f "$TMPFILE1";  fi
+	if [ -f "$TMPFILE2" ]; then  rm -f "$TMPFILE2";  fi
 }
 
 ######################################################################
@@ -75,34 +74,31 @@ finddisowned() {
 
 print_help() {
 	cat <<EOF
-Usage: @ARGV0@ [OPTION]...
+Usage: $ARGV0 [OPTION]...
 Find files that are disowned by package manager.
 
-  -r, --root=PATH     specify an alternative root directory
-  -c, --config=FILE   specify an alternative configuration file
-  -v, --version       print version and exit
-  -h, --help          print help and exit
+Mandatory arguments to long options are mandatory for short options too.
+  -c, --config=FILE  specify an alternate configuration file
+  -r, --root=DIR     specify an alternate root directory
+  -v, --version      print version and exit
+  -h, --help         print help and exit
 EOF
 }
 
 print_version() {
-	echo "@ARGV0@ (pkgmaint) @VERSION@"
+	echo "$ARGV0 (pkgmaint) @VERSION@"
 }
 
 parse_options() {
-	eval set -- "$(
-		getopt  -n "@ARGV0@" -a                  \
-			-l "root:,config:,version,help"  \
-			-o "r:c:vh" -- "$@"
-	)"
+	OPTS=$(getopt -a -n "$ARGV0" -l $LOPTS -o $SOPTS -- "$@") || exit 1
+	eval set -- "$OPTS"; unset OPTS
 	while true; do
 		case $1 in
-		-r|   --root) ROOT=$2        ; shift  ;;
 		-c| --config) CONF=$2        ; shift  ;;
+		-r|   --root) ROOT=$2        ; shift  ;;
 		-v|--version) print_version  ; exit 0 ;;
 		-h|   --help) print_help     ; exit 0 ;;
 		          --) shift          ; break  ;;
-		           *) fatal "internal error"  ;;
 		esac
 		shift
 	done
@@ -113,8 +109,15 @@ parse_options() {
 main() {
 	parse_options "$@"
 
-	[ -d "$ROOT" ] || fatal "specified root directory not found: $ROOT"
-	[ -f "$CONF" ] || fatal "configuration file not found: $CONF"
+	if [ ! -d "$ROOT" ]; then
+		error "root directory not found: $ROOT"
+		exit 1
+	fi
+
+	if [ ! -f "$CONF" ]; then
+		error "configuration file not found: $CONF"
+		exit 1
+	fi
 
 	finddisowned
 }
@@ -131,6 +134,9 @@ trap "atexit"      EXIT
 
 # Globals.
 export LC_ALL=POSIX
+readonly ARGV0="${0##*/}"
+readonly LOPTS="config:,root:,version,help"
+readonly SOPTS="c:r:vh"
 TMPFILE1=
 TMPFILE2=
 
@@ -138,5 +144,5 @@ TMPFILE2=
 
 main "$@"
 
-# vim: cc=72:tw=70
+# vim: cc=72 tw=70
 # End of file.
diff --git a/pkgdiff.in b/pkgdiff.in
--- a/pkgdiff.in
+++ b/pkgdiff.in
@@ -7,7 +7,7 @@
 ######################################################################
 
 fatal() {
-	echo "pkgdiff: $1" 1>&2
+	echo "$ARGV0: $1" 1>&2
 	exit 1
 }
 
@@ -20,8 +20,8 @@ fatal() {
 
 # shellcheck disable=2317
 atexit() {
-	[ -f "$TMPFILE1" ] && rm -f "$TMPFILE1"
-	[ -f "$TMPFILE2" ] && rm -f "$TMPFILE2"
+	if [ -f "$TMPFILE1" ]; then  rm -f "$TMPFILE1";  fi
+	if [ -f "$TMPFILE2" ]; then  rm -f "$TMPFILE2";  fi
 }
 
 # shellcheck disable=2317
@@ -36,8 +36,8 @@ interrupted() {
 ######################################################################
 
 pkgdiff() {
-	[ -f "$1" ] || fatal "file '$1' not found"
-	[ -f "$2" ] || fatal "file '$2' not found"
+	if [ ! -f "$1" ]; then  fatal "file '$1' not found";  fi
+	if [ ! -f "$2" ]; then  fatal "file '$2' not found";  fi
 
 	# https://tldp.org/LDP/abs/html/exitcodes.html
 	# 126 - Command invoked cannot execute.
@@ -59,33 +59,28 @@ pkgdiff() {
 
 print_help() {
 	cat <<EOF
-Usage: pkgdiff [OPTION] FILE1 FILE2
+Usage: $ARGV0 [OPTION] FILE1 FILE2
 Compare software packages' footprints.
 
-  -c, --color     color output
-  -v, --version   print version and exit
-  -h, --help      print help and exit
+  -c, --color    color output
+  -v, --version  print version and exit
+  -h, --help     print help and exit
 EOF
 }
 
 print_version() {
-	echo "pkgdiff @VERSION@"
+	echo "$ARGV0 (pkgmaint) @VERSION@"
 }
 
 parse_options() {
-	eval set -- "$(
-		getopt  -a -n "pkgdiff"          \
-			-l "color,version,help"  \
-			-o "cvh"                 \
-			-- "$@"
-	)"
+	OPTS=$(getopt -a -n "$ARGV0" -l $LOPTS -o $SOPTS -- "$@") || exit 1
+	eval set -- "$OPTS"; unset OPTS
 	while true; do
 		case $1 in
-		-c|  --color) COLOR="--color=always"     ;;
-		-v|--version) print_version  ; exit 0    ;;
-		-h|   --help) print_help     ; exit 0    ;;
-		          --) shift          ; break     ;;
-		           *) fatal "unknown option: $1" ;;
+		-c|  --color) COLOR="--color=always" ;;
+		-v|--version) print_version ; exit 0 ;;
+		-h|   --help) print_help    ; exit 0 ;;
+		          --) shift         ; break  ;;
 		esac
 		shift
 	done
@@ -126,6 +121,9 @@ trap "atexit"      EXIT
 
 # Globals.
 export LC_ALL=POSIX
+readonly ARGV0="${0##*/}"
+readonly LOPTS="color,version,help"
+readonly SOPTS="cvh"
 PKGLIST=
 COLOR=
 TMPFILE1=
@@ -135,5 +133,5 @@ TMPFILE2=
 
 main "$@"
 
-# vim: cc=72:tw=70
+# vim: cc=72 tw=70
 # End of file.
